// Modular re-exports for backward compatibility
export { default as Inventory } from './cafeteria/Inventory'
export { default as WalkInSale } from './cafeteria/WalkInSale'
export { default as Recharges } from './recharges/Recharges'
export { default as NewRecharge } from './recharges/NewRecharge'
export { default as Expenses } from './expenses/Expenses'
export { default as NewExpense } from './expenses/NewExpense'
export { default as Customers } from './customers/Customers'
export { default as Reports } from './reports/Reports'
export { default as Settings } from './settings/Settings'
export { default as EODReconciliation } from './eod/EODReconciliation'
